### ISSUE TITLE
Readme fixes

### ISSUE THREAD

**Issue by filipfranek88** [kpatronas/shellgpt#1]
Hey, nice handy script. Thanks for that. As I went through the README, I encountered a few things I wanted to point out.
```
# add
cd shellgpt
# before
sudo cp ./chatgpt.sh /usr/bin/chatgpt
# and fix the typo in 
cp ./chatgpt ~/.chatgtp/  # where it should be
cp ./chatgpt ~/.chatgpt/
```
Also I was missing information about the BEARER, so I would add: "BEARER expects your API Token that you can create at https://beta.openai.com/account/api-keys"

**Comment by kpatronas** [comment]
Hi! thank you for the issue you spotted, i will fix them
